// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_fCUnccG-Q7ClDpIOGCxlZdg-WP9cIM',
    appId: '1:990709276834:web:0a0d2c166e74c8f881b7fb',
    messagingSenderId: '990709276834',
    projectId: 'soil-moisture-16cec',
    authDomain: 'soil-moisture-16cec.firebaseapp.com',
    databaseURL: 'https://soil-moisture-16cec-default-rtdb.firebaseio.com',
    storageBucket: 'soil-moisture-16cec.firebasestorage.app',
    measurementId: 'G-Z4CZZEPQG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZXjPhN6bU6Urf_9ymvAXS1VAU50dTKk',
    appId: '1:990709276834:android:cf307953ed75477481b7fb',
    messagingSenderId: '990709276834',
    projectId: 'soil-moisture-16cec',
    databaseURL: 'https://soil-moisture-16cec-default-rtdb.firebaseio.com',
    storageBucket: 'soil-moisture-16cec.firebasestorage.app',
  );
}
